const semesters = {
  "BACHELOR OF COMPUTER APPLICATIONS FIRST SEMESTER": 1,
  "BACHELOR OF COMPUTER APPLICATIONS SECOND SEMESTER": 2,
  "BACHELOR OF COMPUTER APPLICATIONS THIRD SEMESTER": 3,
  "BACHELOR OF COMPUTER APPLICATIONS FOURTH SEMESTER": 4,
  "BACHELOR OF COMPUTER APPLICATIONS FIFTH SEMESTER": 5,
  "BACHELOR OF COMPUTER APPLICATIONS SIXTH SEMESTER": 6
};

export default semesters;
